#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# QIIME 2 documentation build configuration file, created by
# sphinx-quickstart on Wed Sep 14 12:55:57 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# ----------------------------------------------------------------------------
# Copyright (c) 2016-2020, QIIME 2 development team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file LICENSE, distributed with this software.
# ----------------------------------------------------------------------------

import sys
import pathlib

import qiime2

root = pathlib.Path(__file__).parent.absolute()
sys.path.insert(0, str(root))

master_doc = "index"
templates_path = ['_templates']
extensions = [
    'q2doc.question',
    'q2doc.qiime1',
    'q2doc.checkpoint',
    'q2doc.command_block',
    'q2doc.usage',
    'q2doc.external_links',
]

source_suffix = '.rst'
project = 'QIIME 2'
copyright = '2016-2020, QIIME 2 development team'
author = 'QIIME 2 development team'
version = qiime2.__release__
release = qiime2.__version__
language = None
exclude_patterns = [
    'sphinx_extensions/plugin_directory/templates',
    'sphinx_extensions/command_block/templates',
]
pygments_style = 'sphinx'
html_theme = 'theme'  # use the theme in subdir 'theme'
html_theme_path = ['.']  # make sphinx search for themes in current dir
html_static_path = ['_static']
html_sidebars = {
    "**": ['globaltoc.html', 'searchbox.html']
}
html_show_sourcelink = False
htmlhelp_basename = 'QIIME2doc'
latex_documents = [
    (master_doc, 'QIIME2.tex', 'QIIME 2 Documentation',
     'QIIME 2 development team', 'manual'),
]
man_pages = [
    (master_doc, 'qiime2', 'QIIME 2 Documentation',
     [author], 1)
]
texinfo_documents = [
    (master_doc, 'QIIME2', 'QIIME 2 Documentation',
     author, 'QIIME2', 'One line description of project.',
     'Miscellaneous'),
]
linkcheck_timeout = 15
mathjax_path = ('https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/'
                'MathJax.js?config=TeX-AMS-MML_HTMLorMML')
